name: CI/CD

on:
  pull_request:
    branches:
      - '*'
    paths-ignore:
      - '**/*.md'
  push:
    branches:
      - main

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      - name: Setup Node 14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install dependencies
        run: |
          npm ci

      - name: Reconfigure Cypress agent
        run: |
          DEBUG=cypress:* cypress version

      # - name: Run tests
      #   run: |
      #     npm run test:e2e
